parameters:
#    rs_hoogstad_tulsie_slesforce.example.class: RsHoogstad\SalesforceJobBundle\Example

services:
#    rs_hoogstad_tulsie_slesforce.example:
#        class: %rs_hoogstad_tulsie_slesforce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
